export enum INVOICE_STATUS {
  PAYED = "PAYED",
  NOT_PAYED = "NOT_PAYED",
  SEMI_PAYED = "SEMI_PAYED",
}

export enum PAYMENT_METHOD {
  CASH = "CASH",
  CARD = "CARD",
  CHECK = "CHECK",
  TRANSFER = "TRANSFER",
  CRYPTO = "CRYPTO",
  OTHER = "OTHER",
}