import { STATUS } from "../enums/common"
import { USER_ROLE } from "../enums/user"
import { UserDto } from "../types/dto/User"

export const defaultClient: UserDto = {
  id: '1',
  firstName: 'Joen',
  lastName: 'Doe',
  username: 'Some username',
  address: 'Nice address',
  zipCode: '123142',
  country: 'Europe',
  email: 'email@email.com',
  workEmail: 'work_email@email.com',
  phoneNumber: '12314212',
  oib: '1241245123123',
  notes: 'Notes',
  status: STATUS.INACTIVE,
  role: USER_ROLE.AGENT,
  password: '1293451',
  webShopCallback: '',
  pickupAddress: 'Pickup address, 122',
  iban: '1241210123876',
  contactPersonPickup: 'Pickup Person',
  contactPersonFinancialOperations: 'Finance Person',
  contactPersonOrganisationOperations: 'Organization Person',
  invoiceEmail: 'invoice_email@email.com',
  contactPersonOther1: 'Other Person 1',
  contactPersonOther2: '',
}

export const emptyClient: UserDto = {
  id: '',
  firstName: '',
  lastName: '',
  username: '',
  address: '',
  zipCode: '',
  country: '',
  email: '',
  workEmail: '',
  phoneNumber: '',
  oib: '',
  notes: '',
  status: STATUS.ACTICE,
  role: USER_ROLE.ADMIN,
  password: '',
  webShopCallback: '',
  pickupAddress: '',
  iban: '',
  contactPersonPickup: '',
  contactPersonFinancialOperations: '',
  contactPersonOrganisationOperations: '',
  invoiceEmail: '',
  contactPersonOther1: '',
  contactPersonOther2: '',
}
